//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int kayitId { get; set; }
        public int kayitUrunId { get; set; }
        public int kayitKatId { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
