//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int sepetId { get; set; }
        public int sepetSiparisId { get; set; }
        public int sepetUrunId { get; set; }
        public string urunAdet { get; set; }
        public decimal toplamFiyat { get; set; }
    
        public virtual Siparis Siparis { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
